osandov/drgn

drgn/helpers/linux/cpumask.py
for_each_cpu is using old attributes "sizeof" and "size". Fix them to
use new ones.
Before patch:
>>> for x in for_each_online_cpu(prog): print(x)
...
File "<console>", line 1, in <module>
File "/home/naota/drgn/drgn/helpers/linux/cpumask.py", line 29, in for_each_cpu
word_bits = 8 * bits.type_.type.sizeof()
AttributeError: '_drgn.Type' object has no attribute 'sizeof'
After patch:
>>> for x in for_each_online_cpu(prog): print(x)
...
0
1
2
3
4
5
6
7
=> helpers: fix for_each_cpu to use new attributes

docs/user_guide.rst, drgn/internal/cli.py
cli currently requires one of --kernel, --core or --pid to be
specified.  Let's assume --kernel so that we can get away with older
env(1) which doesn't understand -S option when writing debug scripts
which uses drgn as the interpreter.  While this is a bit of a kludge,
other options aren't useful on the shebang lines anyway given that
they need an extra dynamic argument.
=> cli: Assume --kernel if no target is specified

libdrgn/linux_kernel.c
Commit f327552229658d85b791c6b0613efb96b8a9da24 introduced a
regression resulting in kernel modules not loaded at the right
offset. This patch fixes the regression.
=> libdrgn: fix regression in kernel module loading

drgn/helpers/linux/list_nulls.py, drgn/helpers/linux/net.py, drgn/helpers/linux/tcp.py, examples/linux/tcp_sock.py, tests/helpers/linux/__init__.py, tests/helpers/linux/test_net.py, tests/helpers/linux/test_tcp.py
Add example script that goes over all TCP sockets and for every socket
prints:
- TCP state;
- IP:port pair;
- cgroup v2 path.
The script shows basic operations with sockets including getting `struct
sock`, `struct inet_sock`, socket fields and cgroup v2 of socket.
It provides output similar to `ss -nt` or `ss -lnt`:
```
% sudo python36 -m drgn examples/linux/tcp_sock.py | shuf -n 5
TIME_WAIT                                       [::1]:2560                                      [::1]:44041
ESTABLISHED                                     [::1]:54178                                     [::1]:11101  system.slice/async-distillery-server.service
LISTEN                                           [::]:3201                                       [::]:0      system.slice/fbflow.service
ESTABLISHED …
```
=> examples: Add tcp_sock.py

examples/linux/tcp_sock.py
In the previous commit used import was removed by mistake. Restore them.
Fixes: 7dd1853 ("examples: Switch tcp_sock to cgroup helpers")
=> examples/tcp_sock: Fix missed import

.editorconfig
Editorconfig is a simple standard for configuring editors based on project specific style settings. I added a basic editorconfig that seems to follow the style of this project (to my knowledge).
- tabs in c code
- 4 spaces in rst and python
- tab override for makefiles (in case the global default changes)
=> .editorconfig: Add editorconfig for configuring style

docs/api_reference.rst, drgn/helpers/linux/kconfig.py, libdrgn/drgn.h.in, libdrgn/language_c.c, libdrgn/program.c, libdrgn/program.h, libdrgn/python/program.c, libdrgn/stack_trace.c, tests/helpers/linux/test_kconfig.py
Since this is my first diff, I would appreciate it if you took a closer look than you normally do, to make sure I'm not overlooking anything.
This should be following the methodology set in #36 pretty exactly. Let me know if anything can be improved though!
I'm not sure if these tests will be fine, if CONFIG_IKCONFIG is not set (as is the case on most systems) I think the test will fail as is. Do you have a way to skip the test in this case, without preventing it from failing if the functionality is actually broken?
Closes #36
=> libdrgn: Add support for looking up reading kernel parameters

libdrgn/kdump.c
prog->kdump_ctx is never really initialized, and the kdump_ctx struct
allocated in drgn_program_set_kdump() is leaked.
WARNING:
I found this bug while working towards https://github.com/osandov/drgn/issues/24 . Once I applied the changes on this PR and tested my bits, `drgn` would hang on exit. That was due to a bug in libkdumpfile as I found later. I submitted a PR for the latter bug here -> https://github.com/ptesarik/libkdumpfile/pull/26
Please do not merge this until https://github.com/ptesarik/libkdumpfile/pull/26 is merged.
=> Fix leak in kdump code

.editorconfig
A tiny change to update style a bit: 
- The new `pyi` file should be treated like python
- While I don't like hard-coding tab-sizes, AFAIK the linux style guide says tabs must be at width 8.
=> editorconfig: Update styles for pyi and c files

libdrgn/kdump.c, libdrgn/linux_kernel.h, libdrgn/program.c, libdrgn/program.h, libdrgn/stack_trace.c
Dump setup (dump + PRSTATUS notes):
```
$ file dump.201912060006
dump.201912060006: Kdump compressed dump v6, system Linux, node exist2crash.vm, release 5.0.0-36-generic, version #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019, machine x86_64, domain (none)
$ ~/libkdumpfile/examples/dumpattr dump.201912060006 cpu
cpu:
1:
pid: 5983
reg:
gs: 0
fs: 0
...
r15: 18446639110723060864
PRSTATUS: [ 00000000000000000000000000000000000000000000000000000000000000005F1700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080C4796689A0FFFF002ED6CF87A0FFFF80583FC29FF0FFFF002ED6CF87A0FFFFE0B8E9048FB3FFFF0700000000000000000000000000000002000000000000000000000000000000E080020000000000A1DB0FC067C4A4D8000E …
```
=> Support stack traces for running threads on kdumps

libdrgn/dwarf_info_cache.c, libdrgn/language.c, libdrgn/language.h, libdrgn/program.c, libdrgn/python/language.c, tests/test_dwarf.py, tests/test_type.py
This is a pretty small and mostly independent change, but I wanted to make sure this is ironed out before moving forward, as there are a couple rough edges I wanted to discuss.
After this, I want to start by tackling the problem of storing template types in `struct drgn_type`, and working on the template support itself (which will probably be another relatively large change).
=> Add cpp language stub

libdrgn/drgn.h.in, libdrgn/dwarf_info_cache.c, libdrgn/python/type.c, libdrgn/type.c, libdrgn/type.h
In anticipation of adding template type pointers in an array to `drgn_type`, I wanted  a way to add additional arrays to this structure. However, currently all variable length arrays are stored by reallocing the drgn_type object to be larger and appended to the object. This works for a single array, but for multiple arrays it won't. 
Since we don't want two methods of storing arrays in drgn_type, and because this was pretty confusing, I refactored the existing arrays into a dynamically allocated array. 
I'm still not 100% sure about the memory allocations (and I'm not sure how to properly run valgrind and other memory debuggers against python/c extensions), so that's the part that will probably need the most review.
After this and #50, I'm going to (hopefully) get template paramter types …
=> Migrate inline allocation to variable length allocation in drgn_type

libdrgn/dwarf_index.c
Loading debuginfo from a kernel with separate or re-combined debuginfo
results in the following failure:
File "/home/jeffm/.local/bin/drgn", line 11, in <module>
load_entry_point('drgn==0.0.3+39.gbf05d9bf', 'console_scripts', 'drgn')()
File "/home/jeffm/.local/lib/python3.6/site-packages/drgn-0.0.3+39.gbf05d9bf-py3.6-linux-x86_64.egg/drgn/internal/cli.py", line 121, in main
prog.load_debug_info(args.symbols, **args.default_symbols)
Exception: invalid DW_AT_decl_file 10
A typical kernel build results in DWARF information with
DW_TAG_compile_unit tags but the objcopy --only-keep-debug and eu-unstrip
commands use DW_TAG_partial_unit tags.  The DWARF indexer only handles
the former, so the file table isn't populated and we get the exception.
Fortunately, the …
=> Enable DWARF indexing to work with partial units

_drgn.pyi, libdrgn/Makefile.am, libdrgn/arch_ppc64.c.in, libdrgn/drgn.h.in, libdrgn/kdump.c, libdrgn/platform.c, libdrgn/platform.h
Add powerpc specific register information required to retrive the
stack traces of the tasks on both live system and from the core dump.
It uses the existing DSL format to define platform registers and
helper functions to initial them. It also adds architecture specific
information to enable powerpc. Current enablement is on little-endian
only.
Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
=> [RFC] libdrgn: add powerpc stack trace support

libdrgn/debug_info.c, tests/test_dwarf.py
Previously, if a class, struct, or enum was both indexed and
incomplete, the check to see if the class was a declaration or
specification during type lookup would always return as a declaration.
This would cause the "complete type" to be looked up again, which
triggers a recursion loop.
One note - I applied this to enums too although I haven't tested that case - as it does the same declaration lookup.
=> libdrgn: Fix lookup of indexed incomplete classes

libdrgn/debug_info.c, libdrgn/dwarf_index.c, libdrgn/dwarf_index.h
Continuation from https://github.com/osandov/drgn/pull/79#discussion_r554248032
I decided to leave the type cache for after the lookup,  as I don't think the extra lookup wll be too bad, and I think it will take a lot of space (and if it does seem slow, it should be an easy fix). This way seems simpler to me, so I think that's where we should start. 
The first commit should only have the minor changes requested, otherwise it should be the same.
=> Convert offsets to addresses and add lookup for indirect dies in type lookup

README.rst, docs/installation.rst, libdrgn/configure.ac, libdrgn/debug_info.c, libdrgn/language.c, libdrgn/program.c
Currently libdrgn requires libelf to be of version 0.175 or
later. This patch allows the library to be compiled with libelf
0.170 (the newest version supported by Ubuntu 18.04 LTS).
Signed-off-by: Serapheim Dimitropoulos <serapheim@delphix.com>
=> libdrgn: stretch minimum supported version of libelf to 0.170

tests/test_dwarf.py
When running tests via pytest, it currently fails with:
```
_______________________ ERROR at setup of test_type_dies _______________________
file /builddir/build/BUILD/drgn-0.0.10/tests/test_dwarf.py, line 193
def test_type_dies(dies):
E       fixture 'dies' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
/builddir/build/BUILD/drgn-0.0.10/tests/test_dwarf.py:193
```
Rename the helper method `test_type_dies` to fix this.
=> tests: rename test_type_dies for pytest compatibility

tests/test_program.py, tests/test_type.py
When running tests via pytest, it currently outputs these warnings:
```
tests/test_program.py:323
/builddir/build/BUILD/drgn-0.0.10/tests/test_program.py:323: DeprecationWarning: invalid escape sequence \(
"memory read callback returned buffer of length 0 \(expected 8\)",
<unknown>:323
<unknown>:323
<unknown>:323
<unknown>:323
<unknown>:323
<unknown>:323: DeprecationWarning: invalid escape sequence \(
tests/test_type.py:865
/builddir/build/BUILD/drgn-0.0.10/tests/test_type.py:865: DeprecationWarning: invalid escape sequence \.
TypeError, "must be _drgn\.Type", self.prog.function_type, None, ()
<unknown>:865
<unknown>:865
<unknown>:865
<unknown>:865
<unknown>:865
<unknown>:865: DeprecationWarning: invalid escape sequence \.
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
=> tests: properly escape regexp strings

examples/linux/cgroup.py, examples/linux/fs_inodes.py, examples/linux/lsmod.py, examples/linux/ps.py, examples/linux/tcp_sock.py
These are executable, so they should have a shebang.
=> examples: add missing shebangs

libdrgn/debug_info.c, libdrgn/debug_info.h, libdrgn/dwarf_index.c, tests/dwarfwriter.py, tests/test_dwarf.py
This ended up being more straightforward than expected - although there are still a couple rough edges (and no tests right now). The biggest change is removing all usages of offsets from the index. 
I'll highlight the biggest questionable things in comments below - hopefully I'll be able to add tests and clean this up a bit more next week :).
=> Add basic support for parsing DWARF type units

libdrgn/dwarf_index.c, tests/dwarfwriter.py, tests/test_dwarf.py
This isn't completely done, unfortunately, but I wanted to get it out in the open at least for now. The main thing missing is real tests, right now I'm using your patch to convert every test into an indirect one (so right now the tests don't test normal dwarf). Do you think we should just duplicate every test into a indirect and non-indirect variant? 
Most of this is unfortunately just moving code around, the main strategy is to record the "context" of an attribute when we see an indirect (in the instruction), and use that to re-create the "real" instruction when later parsing. To do this I (unfortunately) needed to make several additional instructions (to encode this context), but I don't know if there's a cleaner way to do this. 
Let me know what you think - hopefully I will have time …
=> Add support for DW_FORM_indirect

drgn/helpers/linux/cpumask.py, drgn/helpers/linux/nodemask.py, tests/helpers/linux/__init__.py, tests/helpers/linux/test_cpumask.py, tests/helpers/linux/test_nodemask.py
Sometimes we want to traverse numa nodes in the system,
so add kernel nodemask helpers to support this.
Signed-off-by: Qi Zheng <zhengqi.arch@bytedance.com>
=> helpers: add kernel nodemask helpers

drgn/helpers/linux/net.py, tests/helpers/linux/test_net.py
Add a helper to find the "struct net_device *" object given the
corresponding interface index.  As an example:
>>> netdev = find_netdev_by_index(prog.object("init_net"), 1)
>>> netdev.name.string_().decode()
'lo'
Currently looking up by name is non-trivial to do in drgn, see kernel
function net/core/dev.c:netdev_name_node_lookup() for reference.  Use
socket.if_nametoindex() instead:
>>> dummy = find_netdev_by_index(prog.object("init_net"), \
...                              socket.if_nametoindex("dummy0"))
>>> dummy.name.string_().decode()
'dummy0'
Also add a test for this new helper to tests/helpers/linux/test_net.py.
Signed-off-by: Peilin Ye <peilin.ye@bytedance.com>
=> helpers: Add netdev_get_by_index()

drgn/helpers/linux/net.py, tests/helpers/linux/test_net.py
Hi Omar,
Here's netdev_get_by_name() and a test, as we discussed.  Currently the `name` parameter is `str` since I didn't find the `str` version of `IntegerLike`; should we use something like `Path`?
---
Add a helper to get the network device ("struct net_device *") given an
interface name.  As an example:
>>> netdev = netdev_get_by_name(prog["init_net"], "lo")
>>> netdev.ifindex.value_()
1
Or pass a "Program" as the first argument, and let the helper find in
the initial network namespace (i.e. "init_net"):
>>> netdev = netdev_get_by_index(prog, "dummy0")
>>> netdev.ifindex.value_()
2
Also add a test for this new helper to tests/helpers/linux/test_net.py.
This helper simply does a linear search over the name hash table of the
network namespace, since implementing hashing in drgn is …
=> helpers: Add netdev_get_by_name()

drgn/helpers/linux/net.py, tests/helpers/linux/test_net.py
Hi Omar,
Another simple helper to iterate over all `struct net`s.  Looking up by name is impractical since Linux kernel doesn't maintain name for netns.  One way would be let drgn read the corresponding nsfs node directly e.g. `/var/run/netns/foo`, but different userspace tools bind-mount `/proc/$PID/ns/net` to different places (e.g. `/var/run/netns/*` for `ip`, `/var/run/docker/*` for Docker)...I think a `for_each_` helper would be sufficient for now.
thanks,
ypl
---
Add a helper to iterate over all network namespaces in the system.  As
an example:
>>> for net in for_each_netns(prog):
...     if netdev_get_by_name(net, "enp0s3"):
...         print(net.ipv4.sysctl_ip_early_demux.value_())
...
1
Also add a test for this new helper to tests/helpers/linux/test_net.py.
=> helpers: Add for_each_netns()

drgn/helpers/linux/net.py, drgn/helpers/linux/tc.py, tests/helpers/linux/test_net.py, tests/helpers/linux/test_tc.py
Hi Omar,
Two more helpers:
1. netdev_for_each_tx_queue(), this one is simple.
2. qdisc_lookup(), this one is for debugging Traffic Control (TC) issues.  I created new files for it (and its test) since TC setup is more complicated (I'm already depending on 5 kernel configs for testing a semi-realistic scenario, see commit message below), and we are planning to add more TC helpers :-)
I'm using `pyroute2` for TC testing, some questions:
1. Is it okay to use a `try` block around `pyroute2` `import`s and skip the entire `TestTc` upon `ImportError`?
2. I've tested it locally with several kernel configs on and off.  What should I do to let GitHub CI use `pyroute2` (and enable those kernel configs), or could you make that happen?
3. Should I, and/or where should I document that `drgn` testing …
=> Add netdev_for_each_tx_queue() and qdisc_lookup()

libdrgn/dwarf_index.c
Firstly, there's no rush on the pulls I'm submitting at all - I'm just putting it on the queue for discussion later on.
In larger binaries, there can be a large number of CUs, and since we
store an abbrev table for each CU the extra space starts to add up.
The simplest way to mitigate this is to shrink the vectors before
saving them.
On a large binary, I noticed a memory reduction from 20.4G RES to 18.6G
RES (on initial load-in).
I'm not sure if this will cause a CPU regression, but at worst this would be an extra copy (and hopefully a realloc is cheaper than that), but I think the memory savings are worth it. I don't think a length is stored anywhere for abbrev tables, so I don't think we can pre-calculate the size here.
=> dwarf_index.c: Shrink abbrev tables before saving them in CUs

libdrgn/binary_search_tree.h, libdrgn/splay_tree.c
When linking libdrgn as a static library, the name 'splay_tree' can
conflict with splay-tree.h in gcc (namely splay_tree_splay).
Rename relevant functions to have a 'drgn_' prefix
=> splay_tree.c: Rename splay_tree to avoid conflicts with splay-tree.h

libdrgn/debug_info.c, tests/test_dwarf.py
In C++ enums can be a typedef to an int, not just an int itself.
The one questionable part is that we store the underlying type and not the typedef in the enum - but that seems fine to me. However, I think I should be able to store the typedef if we would like as well, I just have to see if it's being used as if it was an int elsewhere.
=> libdrgn: Follow typedefs in enum backing type lookup

libdrgn/dwarf_info.c
On older gcc version e.g. 7.3.1 , we get following compilation error
CC       libdrgnimpl_la-dwarf_info.lo
../../libdrgn/dwarf_info.c:181:51: error: initializer element is not
constant
static const size_t DRGN_DWARF_INDEX_NUM_SHARDS = 1 <<
DRGN_DWARF_INDEX_SHARD_BITS;
This fixes the compilation error on older versions of gcc
Signed-off-by: Alakesh Haloi <alakesh.haloi@gmail.com>
=> libdrgn: fix for compilation error

.github/workflows/ci.yml, drgn/helpers/linux/__init__.py
With mypy 0.920, two warnings appear on current main:
```
$ mypy --strict --no-warn-return-any drgn _drgn.pyi
drgn/helpers/linux/__init__.py:36: error: Need type annotation for "__all__" (hint: "__all__: List[<type>] = ...")
drgn/helpers/linux/__init__.py:38: error: unused "type: ignore" comment
Found 2 errors in 1 file (checked 33 source files)
```
The "unused" type:ignore directive was necessary for prior versions, so
add --no-warn-unused-ignores, so that we pass on multiple versions.
Apply a List[str] annotation to the __all__ variable to silence the
other error.
=> Silence mypy warnings

scripts/iwyu.py
This minor change is a quality of life improvement ensuring developers
receive more warnings and diagnostics in their editors.
Signed-off-by: Kevin Svetlitski <svetlitski@fb.com>
=> Ensure compile_commands.json contains `-Wall`

_drgn.pyi, drgn/helpers/linux/idr.py, drgn/helpers/linux/pid.py, drgn/helpers/linux/radixtree.py, libdrgn/helpers.h, libdrgn/linux_kernel_helpers.c, libdrgn/python/drgnpy.h, libdrgn/python/helpers.c, libdrgn/python/module.c, tests/helpers/linux/test_pid.py
This was split off from #129 per @osandov's request.
In preparation for introducing an API to represent threads, the linux
helper iterators, radix_tree_for_each, idr_for_each, for_each_pid, and
for_each_task have been rewritten in C. This will allow them to be
accessed from libdrgn, which will be necessary for the threads API.
Signed-off-by: Kevin Svetlitski <svetlitski@fb.com>
=> Rewrite linux helper iterators in C

drgn/helpers/linux/net.py, tests/helpers/linux/test_net.py
Add helpers to convert between sockets and inodes.  As an example:
>>> file = fget(task, fd)
>>> sock = SOCKET_I(file.f_inode)
>>> sock.type.value_()
2
>>> import socket
>>> int(socket.SOCK_DGRAM)
2
>>> inode = SOCK_INODE(sock)
Also add tests for the new helpers to tests/helpers/linux/test_net.py.
=> helpers: Add SOCKET_I() and SOCK_INODE()

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, libdrgn/build-aux/gen_constants.py
In my past Python projects I've relied on pre-commit hooks to catch lint errors before I even push my branch to CI. I found this to be super useful (and have already re-pushed quite a few drgn commits after realizing I forgot to run black / isort / mypy).
This PR adds support for the pre-commit tool, including the equivalent checks which are run during test/lint stages. Developers can install it locally with `pre-commit install --install-hooks`, where it will check your changed files prior to each commit. I ran the pre-commit hooks across all files and caught one black reformatting (which may have been my fault anyway...), which I included here. Finally, I updated the CI steps to directly call pre-commit for linting.
This means that all linter versions and arguments can be stored in a …
=> Add pre-commit

_drgn.pyi, libdrgn/drgn.h.in, libdrgn/program.c, libdrgn/python/program.c, libdrgn/symbol.c, tests/test_symbol.py
This PR aims to address #47 by implementing `Prog.symbols()`, which searches for global and local symbols by a given name. Under the hood it's implemented with `drgn_program_find_symbols_by_name()` which is heavily adapted from `drgn_program_find_symbol_by_name()`, except it may return a list, and it doesn't terminate early after finding the first symbol.
I did verify this works by loading a kernel dump and trying out a few symbols. "name_show" is commonly used in sysfs, so it has several definitions. "slab_bug" is just a static function.
```python
>>> prog.symbol("name_show")
File "<console>", line 1, in <module>
LookupError: could not find symbol with name 'name_show'
>>> prog.symbols("name_show")
[Symbol(name='name_show', address=0xffffffff927175d0, …
```
=> Add methods for finding non-global symbols by name

libdrgn/program.c
Fixes the heap-use-after-free error uncovered by ASAN noted by @osandov in the comments on #151.
Running the test suite with ASAN enabled revealed that when
the current target was a userspace core dump, the `crashed_thread`
member of `struct drgn_program` was being freed twice – once indirectly
via `drgn_thread_set_deinit`, and once explicitly in `drgn_prog_deinit`.
=> Fix double-free of `crashed_thread`

libdrgn/Makefile.am, libdrgn/configure.ac
[AddressSanitizer (a.k.a ASAN)](https://github.com/google/sanitizers/wiki/AddressSanitizer) is incredibly useful during development, especially when dealing with non-deterministic behavior where re-running the code under a debugger won't necessarily reproduce the bug each time. In order not to break any existing workflows, building with ASAN is opt-in (via `--enable-asan`).
I had originally added this just for myself to make debugging easier, but I figured I may as well upstream it given how useful it's been.
=> Add autoconf option to enable ASAN

_drgn.pyi, docs/user_guide.rst, libdrgn/drgn.h.in, libdrgn/program.c, libdrgn/program.h, libdrgn/python/program.c, tests/helpers/linux/test_threads.py, tests/linux_kernel/vmcore/test_vmcore.py, tests/test_thread.py
Currently only supported for user-space crash dumps. E.g. no support
for live user-space application debugging of kernel debugging
Closes #144
Signed-off-by: Mykola Lysenko <mykolal@fb.com>
=> Add drgn.Program.main_thread()

scripts/iwyu.py
Minor quality of life improvement.
Previously iwyu.py overwrote the value of the `CFLAGS` environment
variable regardless of whether it was already set. This was very
frustrating when trying to set custom `CFLAGS` to be used in the
generation of compile_commands.json, so the script now only sets
`CFLAGS` if it is not already present in the environment.
Signed-off-by: Kevin Svetlitski <svetlitski@fb.com>
=> Make iwyu.py respect the `CFLAGS` environment variable

drgn/helpers/linux/dmesg.py, tests/helpers/linux/test_dmesg.py
Helper allows user to obtain the raw contents of dmesg. This would be useful to have within drgn itself for debugging.
=> Adding helper to get the kernel ring buffer

drgn/helpers/linux/slab.py, tests/helpers/linux/test_slab.py
Adding additional helpers to view slab info for debugging.
Allows for printing slabs, obtainig the struct kmem_cache object
corresponding to a slab and obtaining all slab objects of a given
type.
=> helpers: porting slab allocating debugging tools to drgn helpers

.packit.yaml
Builds will show up under https://copr.fedorainfracloud.org/coprs/g/meta/drgn/
Also start building for ELN (which tracks the next RHEL/CentOS major release)
=> Use dedicated copr for packit builds

.packit.yaml
Upstream pinned ELN to use POWER9 builders, reenabling to see if that fixed it. cc @praiskup
=> packit: reenable fedora-eln-ppc64le builds

libdrgn/drgn.h.in, libdrgn/dwarf_info.c, libdrgn/object.c, libdrgn/object.h, libdrgn/python/error.c, tests/test_object.py
We still do not support reading values from these integers (ie: object support)
but we at least provide type information for them now. When not supported,
throw an error.
I tried to compile a list of places that needed to be checked with this type format:
```
* [[file:libdrgn/object.c::drgn_object_read_reference(const struct drgn_object *obj,]]
- Gated to only support bit sizes 64 or less
* [[file:libdrgn/object.c::drgn_object_read_bytes(const struct drgn_object *obj, void *buf)]]
- Seems to support large bit sizes
* [[file:libdrgn/object.c::drgn_object_read_value(const struct drgn_object *obj, union drgn_value *value,]]
- Seems to be covered by ~read_reference~
* [[file:libdrgn/object.c::drgn_object_convert_signed(const struct drgn_object *obj, uint64_t bit_size,]]
- Covered by …
```
=> object.c: Add support for parsing 128 bit integers

libdrgn/dwarf_info.c, tests/test_dwarf.py
Previously `drgn` did not recognize the	`DW_ATE_UTF` encoding for base types, and consequently could not handle the [UTF character types defined by C++](https://en.cppreference.com/w/cpp/language/types#char16_t) (i.e. `char8_t`, `char16_t`, and `char32_t`). This has been remedied, and a corresponding test case added to prevent regressions.
=> Add support for UTF character base types

libdrgn/dwarf_info.c, libdrgn/language.h, libdrgn/language_c.c, tests/dwarfwriter.py, tests/test_dwarf.py
Previously (see test) incomplete types were not found by find_complete if they were in namespaces, even though they were indexed by drgn - this pull corrects this. This does do a full traversal of a CU to get the path, but hopefully that will not be too slow since #124 (and if it is, we can disable this for C if you would like). 
I needed to add a small feature to the test suite to support this - which allows us to use ref4 to reference any die rather than just the top-level. 
I do have patches for extending this into classes as well to handle nested classes, but we (without other patches I have floating) don't support indexing within classes yet anyway. The big pitfall for that is that class dies might not have names and just have a signature - in which case we have to follow the …
=> Add support for looking up incomplete types in namespaces

drgn/helpers/linux/llist.py, tests/linux_kernel/helpers/test_llist.py, tests/linux_kernel/kmod/drgn_test.c
There was one merging mistake in PR: https://github.com/osandov/drgn/pull/194. This is new version of same PR with review comments addressed.
It has been tested with test cases added as part of this PR:
`test_llist_empty (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_first_entry (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_first_entry_or_null (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_for_each (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_for_each_entry (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_is_singular (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
test_llist_next_entry (tests.linux_kernel.helpers.test_llist.TestLlist) ... ok
`
=> Llist helpers v2

drgn/helpers/linux/slab.py, tests/linux_kernel/helpers/test_slab.py, tests/linux_kernel/kmod/drgn_test.c
This helper function identifies the slab cache (if any) the object at the given address belongs to. This will be useful for a future helper function which prints the stack trace with more information about each item on the stack.
=> Implement find_containing_slab_cache helper function

libdrgn/dwarf_info.c
abbrevation => abbreviation; caught by Debian's lintian
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
=> Fix spelling error

libdrgn/memory_reader.c, libdrgn/memory_reader.h, libdrgn/program.c
makecoredump will exclude zero pages. We found a core file where a
structure straddled a page boundary and the end of the structure
was all zeros so the page was excluded and we were generating a
FaultError trying to access the structure.
This change reverts a portion of that behaviour such that when we are
debugging a kernel core we go back to the zero fill behaviour. To do this
we go back to creating segments based on memsz instead of filesz and
handling the filesz->memsz gap in drgn_read_memory_file.
Fixes: 02912ca7d073 ("libdrgn: fix handling of p_filesz < p_memsz in core dumps")
Signed-off-by: Glen McCready <gkm@mysteryinc.ca>
=> libdrgn: Zero fill excluded pages in kernel core dumps rather than FaultError

.packit.yaml
Something changed recently in PackIt and it no longer generates a
changelog if the rpmautospec macro is present. This ends up breaking
EPEL 8 builds, which apparently don't support rpmautospec properly yet
(see https://pagure.io/fedora-infra/rpmautospec/issue/204).
Signed-off-by: Davide Cavalca <dcavalca@fb.com>
=> packit: disable rpmautospec

tests/linux_kernel/helpers/test_slab.py
Hi all,
Running `test_find_containing_slab_cache_invalid()` without the `drgn_test` Linux kernel module gives a `KeyError`:
```
File ".../tests/linux_kernel/helpers/test_slab.py", line 169, in test_find_containing_slab_cache_invalid
find_containing_slab_cache(self.prog, self.prog["drgn_test_va"]),
KeyError: 'drgn_test_va'
```
Use the `@skip_unless_have_test_kmod` tag.  Fixes: 79ea6589c28c ("drgn.helpers.linux.slab: add find_containing_slab_cache helper")
Thanks,
Peilin Ye
=> Fix drgn_test_va KeyError when running test_find_cotaining_slab_cache_invalid()

drgn/helpers/linux/slab.py
`find_containing_slab_cache` is supposed to returns NULL when encountered a page which does not exist. This is detected when accessing page flags gives us a fault error. However, this is not checked correctly in the current implementation. This commit fixes this issue.
=> Fix find_containing_slab_cache's behavior when the page does not exist

drgn/helpers/common/memory.py
Change `drgn.helpers.memory` to `drgn.helpers.common.memory`. Oops my bad - forgot to update this 🤦‍♂️ This should be the [only one](https://github.com/osandov/drgn/search?q=drgn.helpers.memory).
=> Fix drgn.helpers.common.memory introductory documentation

_drgn.pyi, libdrgn/drgn.h.in, libdrgn/dwarf_info.c, libdrgn/dwarf_info.h, libdrgn/python/stack_trace.c, libdrgn/stack_trace.c, tests/linux_kernel/kmod/drgn_test.c, tests/linux_kernel/test_stack_trace.py
I know you mentioned in #134 that listing variables in a stack frame would be something that is made part of the Scopes API (#123). That makes sense, but given that the Scopes API may be a long time coming, and it will need to cover a lot of complexity, I wanted to share this small implementation of this idea. No expectations here (even of review, let alone merging :smile: ). I'm starting to play around with debugger code built on top of this, so I'm personally finding it useful.
=> Add StackFrame.locals() method

libdrgn/dwarf_info.c, libdrgn/orc_info.c
qsort_r is a non-standard glibc extension and turns out to be the only thing that prevents drgn from working on a musl system. "Fix" the use of qsort_r by switching it to qsort with a thread local variable for the parameter.
Tested in a clean chroot install of musl voidlinux.
Signed-off-by: Boris Burkov <boris@bur.io>
=> qsort_r -> qsort with TLVs

.packit.yaml
Packit is failing because the examples directory doesn't exist since commit a0a54edc1f1d ("Create contrib directory"). Let's work around it in our post-upstream-clone step until we cut the next release and update the RPM spec.
Signed-off-by: Omar Sandoval <osandov@osandov.com>
=> packit: temporarily work around examples directory

libdrgn/language_c.c, tests/libdrgn.py, tests/test_language_c.py
Previously, attempting to lookup a type with template parameters via `prog.type()` would result in an "invalid character" error message. This has been remedied by properly handling template parameters in the C++ lexer, enabling type lookups as desired.
Signed-off-by: Kevin Svetlitski <svetlitski@meta.com>
=> Correctly interpret template parameters in the C++ lexer

drgn/helpers/linux/fs.py
It's allowable for task->files to be NULL. Handle this case gracefully by returning without yielding any files.
=> helpers/linux/fs: for_each_file: handle NULL files

libdrgn/language_c.c
Found via [CodeChecker](https://codechecker.readthedocs.io/en/latest/) static analysis.
=> Fix memory leak in `c_format_compound_object`

_drgn.pyi, docs/advanced_usage.rst
drgn is able to lookup some special metadata for the Linux kernel, sometimes even without debuginfo. For users who may expect that Program.object() will only return objects corresponding to variables, these metadata are unexpected and can be quite useful. Regardless, they're currently undocumented. Add documentation under Advanced Usage for these, and reference it in the Program.object() docstring.
=> Document the linux kernel object finder

_drgn.pyi
Object attributes which are not changed after the object's creation have been marked with the `Final` type attribute. The primary utility of this change is that some Python type checkers, [such as Pyre](https://pyre-check.org/docs/errors/#optional-attributes), rely on the presence of the `Final` attribute to determine whether `Optional` values have been validated as being present before their contents are accessed.
This is an issue I ran into myself while trying to typecheck a codebase which uses `drgn`'s scripting interface.
=> Mark immutable attributes as `Final` in type stubs

docs/advanced_usage.rst
The parameters of the read_file function in the example are swapped. This matches the parameters order used by py_memory_read_fn.
=> Fix example for add_memory_segment

_drgn.pyi, drgn/helpers/linux/idr.py, libdrgn/linux_kernel_helpers.c, tests/linux_kernel/helpers/test_idr.py, tests/linux_kernel/kmod/drgn_test.c
This changeset adds support for non-radix tree based idrs in drgn, so that drgn idr helpers can be used with kernels prior tha v4.11.
I have also added idr test cases separately. So far idr test cases were covered by radix tree test cases (since idr helpers were available only for radix-tree base idrs.
=> Non radix tree idr support rc1

contrib/fs_inodes.py
When inode_path returns None and it's passed to fsdecode, I get TypeError exception:
```
File "/usr/lib64/python3.10/os.py", line 823, in fsdecode
filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Thus catch both exception types.
=> fs_inodes: catch proper exception for None path

contrib/mount.py
Provides crash-like output:
```
Mount            Type         Devname      Dirname
ffff8fed001d8500 rootfs       rootfs       /
ffff8fed06a197c0 proc         proc         /proc
ffff8fed06a192c0 sysfs        sysfs        /sys
ffff8fed06a18c80 devtmpfs     devtmpfs     /dev
ffff8fed06a18b40 securityfs   securityfs   /sys/kernel/security
ffff8fed06a19cc0 tmpfs        tmpfs        /dev/shm
ffff8fed06a18500 devpts       devpts       /dev/pts
ffff8fed06a18dc0 tmpfs        tmpfs        /run
...
```
=> add mount.py contrib script

drgn/helpers/linux/cgroup.py
Since Linux kernel commit 8520e224f547 ("bpf, cgroups: Fix cgroup v2 fallback on v1/v2 mixed mode") (in v5.15), the sock_cgroup_data contains directly cgroup member (of struct cgroup * type).
=> fix sock_cgroup_ptr for v.5.15+

scripts/build_dists.sh, scripts/build_manylinux_in_docker.sh
I've had this change sitting around in my local tree for a bit and thought I'd share it. I frequently build & share "beta" development releases in wheel format, and I only build one Python release (Python 3.6 😢 ). This adds an optional parameter to the wheel building scripts to specify a Python version, which saves a fair bit of time. I don't know if anybody else does this but it may be a useful change to have?
=> Allow building just one Python release

docs/advanced_usage.rst, docs/api_reference.rst, docs/user_guide.rst, drgn/__main__.py, drgn/cli.py, setup.py
It's quite useful to run drgn's CLI from a user-provided script. One reason is saving the drgn core dump and debuginfo setup into a script to more easily start analysis. Another might be to replace drgn's debuginfo loading scheme with one customized to a different environment. Or, a script might want to handle errors by allowing an interactive user to examine the program themselves.
To serve all of these cases and more, separate out the logic of running the drgn CLI from the internal logic relating to argument parsing, choosing the correct target, and loading debuginfo. While this may seem like a simple case of code.interact, there are several important internal features drgn provides in its CLI: a custom displayhook, a custom readline completer, a history file, and of course the logic to …
=> cli: Separate the main function from the CLI

contrib/vmstat.py
The script mimics what crash> kmem -V does, the script reports the following:
```
Event                                           Count
VM_ZONE_STAT:
NR_FREE_PAGES                                  512147
NR_ZONE_LRU_BASE                               234271
NR_ZONE_INACTIVE_ANON                          234271
NR_ZONE_ACTIVE_ANON                               196
NR_ZONE_INACTIVE_FILE                           97200
NR_ZONE_ACTIVE_FILE                            110611
NR_ZONE_UNEVICTABLE                              1000
NR_ZONE_WRITE_PENDING                              84
NR_MLOCK                                            0
NR_BOUNCE                                           0
NR_ZSPAGES                                          0
NR_FREE_CMA_PAGES                                   0 …
```
=> add vmstat.py script to contrib

drgn/helpers/linux/sched.py, tests/linux_kernel/helpers/test_sched.py
The helper function returns a list with load
averaged over the last 1, 5 and 15 minutes.
=> Introduce loadavg helper.

vmtest/vm.py
Sometimes one can see an OOM with a higher number of SMP count while still having 2G of memory.
=> tests: limit SMP count to 8 at maximum

libdrgn/dwarf_info.c, tests/test_dwarf.py
GCC appears to use data8 at -1 when reporting zero length arrays, this patch adds support and a test for that behavior.
dwarf_info.c: Remove check for sdata on quirk for array length == 0
I also added a test to avoid this case regressing in the future
See https://github.com/facebookexperimental/object-introspection/pull/77#issuecomment-1439156748
=> Expand DW_AT_upper_bound to include other types of int

contrib/kernel_sys.py
This script mimics crash>sys and provides the following output:
```
CPUS             16
DATE             Fri Jan 27 20:26:24 2023
UPTIME           1 day, 7:29:37
LOAD AVERAGE     0.00, 0.00, 0.00
TASKS            317
NODENAME         tw
RELEASE          6.1.7-1-default
VERSION          #1 SMP PREEMPT_DYNAMIC Wed Jan 18 11:12:34 UTC 2023 (872045c)
MACHINE          x86_64
MEMORY           12.67 GiB
```
=> add sys.py to contrib

contrib/tcp_sock.py
In v5.18, it's actually hlist_nulls_head what is used for items of inet_hashinfo::listening_hash. With the change it works for all releases starting with v4.9. The version 4.4 is not supported right now (nulls head list is probably not known at the time).
Fixes: #268
=> Fix TCP listing contrib script

contrib/ps.py
New output of the command is:
```
PID     PPID    CPU  ST    VMS     RSS  MEM%  COMM
1       0       0    S   10.4M    6.5M   0.4 init
2       0       0    S       0       0   0.0 [kthreadd]
...
263     1       4    S    2.4G  163.5M   9.5 python3
264     1       5    S    2.4G  163.5M   9.5 python3
265     1       6    S    2.4G  163.5M   9.5 python3
266     1       10   S    2.4G  163.5M   9.5 python3
267     1       12   S    2.4G  163.5M   9.5 python3
268     1       13   S    2.4G  163.5M   9.5 python3
269     1       14   S    2.4G  163.5M   9.5 python3
270     1       15   S    2.4G  163.5M   9.5 python3
271     1       16   S    2.4G  163.5M   9.5 python3
...
```
=> contrib: add memory statistics to ps.py

contrib/vmmap.py
Mimics `cat /proc/$pid/maps` and the script output is:
```
Start        End          Flgs   Offset Dev   Inode            File path
55dee5284000-55dee53f3000 r-xp 00000000 fd:02 10515            /usr/lib/systemd/systemd
55dee53f3000-55dee5441000 r--p 0016f000 fd:02 10515            /usr/lib/systemd/systemd
55dee5441000-55dee5442000 rw-p 001bd000 fd:02 10515            /usr/lib/systemd/systemd
55dee5f4c000-55dee615d000 rw-p 00000000 00:00 0
7f5fc801c000-7f5fc8024000 r-xp 00000000 fd:02 1181379          /usr/lib64/libffi.so.7.1.0
7f5fc8024000-7f5fc8224000 ---p 00008000 fd:02 1181379          /usr/lib64/libffi.so.7.1.0
7f5fc8224000-7f5fc8225000 r--p 00008000 fd:02 1181379          /usr/lib64/libffi.so.7.1.0
```
...
=> contrib: add vmmap.py script

drgn/helpers/linux/mm.py, libdrgn/arch_s390x.c, tests/linux_kernel/__init__.py
Add support for walking s390x page tables. This supports up to 5 level page table walking and huge/large pages. In order to figure out the level of paging used, we read the first entry of the pgd, which is always mapped for lowcore access and use the level bits of the next page table. This is because drgn passes mm::pgd as pgtable argument to the walker function which doesn't contain the ASCE bits.
Signed-off-by: Sven Schnelle <svens@linux.ibm.com>
=> libdrgn: add s390x pagetable walk support

libdrgn/linux_kernel.c
With GCC 13.1.1 and the recommended build
setup (`CONFIGURE_FLAGS="--enable-compiler-warnings=error"`), I get the following failure:
```
In function 'linux_kernel_get_vmemmap',
inlined from 'linux_kernel_object_find' at ../../libdrgn/linux_kernel_object_find.inc.strswitch:34:12:
../../libdrgn/linux_kernel.c:370:23: error: 'address' may be used uninitialized [-Werror=maybe-uninitialized]
370 |                 err = drgn_object_set_unsigned(&prog->vmemmap, qualified_type,
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
371 |                                                address, 0);
|                                                ~~~~~~~~~~~
../../libdrgn/linux_kernel.c: In function 'linux_kernel_object_find':
../../libdrgn/linux_kernel.c:361:26: note: …
```
=> libdrgn: linux_kernel: Fix compiler warning

contrib/dump_btrfs_bgs.py
Add a script to dump all btrfs block groups and decode relevant members to contrib.
```
Example output for a given filesystem:
BG at 536870912
flags: BTRFS_BLOCK_GROUP_DATA (0x1)
length: 134217728
used: 0
pinned: 0
reserved: 0
runtime_flags: BLOCK_GROUP_FLAG_ZONE_IS_ACTIVE|BLOCK_GROUP_FLAG_SEQUENTIAL_ZONE (0x120)
zone_unsuable: 0
BG at 671088640
flags: BTRFS_BLOCK_GROUP_SYSTEM|BTRFS_BLOCK_GROUP_DUP (0x22)
length: 134217728
used: 16384
pinned: 0
reserved: 0
runtime_flags: BLOCK_GROUP_FLAG_ZONE_IS_ACTIVE|BLOCK_GROUP_FLAG_SEQUENTIAL_ZONE (0x120)
zone_unsuable: 16384
BG at 805306368
flags: BTRFS_BLOCK_GROUP_METADATA|BTRFS_BLOCK_GROUP_DUP (0x24)
length: 134217728
used: 131072
pinned: 0
reserved: 0
runtime_flags: BLOCK_GROUP_FLAG_ZONE_IS_ACTIVE|BLOCK_GROUP_FLAG_SEQUENTIAL_ZONE (0x120) …
```
=> contrib: add btrfs block group dumper

.github/workflows/ci.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, .github/workflows/vmtest-build.yml
Use the "hyphen release" syntax to specify the latest version between 3.12.0-beta.1 and 3.12. It's unclear whether this will actually work to bring in the real releases of 3.12 when they happen, but I think the only way to find out would be to try it out.
=> Add Python 3.12 to CI

libdrgn/linux_kernel.h, libdrgn/program.c
The makedumpfile flattened format is occasionally seen by users, but is not read by libkdumpfile and thus unsupported by Drgn. A simple 'reassembly' process is all that is necessary to allow Drgn to open the vmcore, but this fact isn't easily discoverable, resulting in issues like #344. To help users, detect this when we're testing for kdump signatures, and raise an error with reassembly instructions.
For further details on the flattened format, consult makedumpfile(8), particularly the sections documenting options -F and -R.
=> libdrgn: detect flattened vmcores and raise error

libdrgn/arch_x86_64.c, libdrgn/register_state.c, libdrgn/register_state.h
Sometimes a stack trace cannot be unwound because of pc being zero and we end up with a single empty frame: `0: 0x0`. In these cases, we can assume a NULL function pointer was called and then modify RIP and RSP so that they are associated with the frame of the "caller of the NULL function pointer". This allows the stack to be unwound, revealing every frame below the NULL call. A new function is added to perform this manipulation of registers, and is then used within the x86_64 fallback unwinder where attempting to get registers from the frame pointer fails and pc is found to be zero.
=> Handle zero pc in x86_64 fallback unwind

contrib/ps.py
Enhanced the `ps.py` script and made it more modular to support the following options:
[-a | --active] thread on each CPU
[-c | --childs] processes info
[--cpus] Ready/running proccesses for the given cpu
[-d | --detailed] information (in addition to standard)
[--hierarchy] of all parent processes
[-k | --kthread] information on the given kernel threads
[-u | --uthread] information on the given user-space threads
[-t | --threads] information on the given threads
These options make the scipt more versatile and useful.
=> script/ps: enhanced ps script

.pre-commit-config.yaml, drgn/__init__.py
The "pre-commit-hooks" repo contains a few hooks that enforce some nice, common sense guidelines. The "vermin" hook checks compatibility with a supplied minimum Python version requirement, both checking the syntax and standard library usage. It's very helpful for identifying incompatible code before getting to the CI steps.
---
I don't believe I proposed these hooks in my initial pull request, but I've been using them in some of my other projects and find them quite helpful.
The pre-commit-hooks are a bunch of fast, common-sense checks that I've never really had cause issues, but they can catch some obvious things. Some of them would overlap with Black for the Python code, but they will apply to non-python files as well.
The vermin hook is the main reason I submitted this. It has …
=> Add more pre-commit hooks

contrib/ptdrgn.py
I finally got around to getting Drgn working with [ptpython](https://github.com/prompt-toolkit/ptpython) and it's pretty glorious. One particular item that's great is that it has a good multi-line code editor, so you can write multi-line loops, etc, and get automatic indentation, and you can go back and fix mistakes prior to the current line. I added in C syntax highlighting for Drgn objects + types, and I'd like to at some point get it to do completion for object members.
The actual code doing it was just going to live in `~/bin/ptdrgn`, but I figured I could at least share it. It's full of hacks and implementation details, but this is the `contrib` directory, so maaaybe it's ok?
=> contrib: Add ptdrgn.py script to run interactively via ptpython

_drgn.pyi, drgn/cli.py, drgn/internal/sudohelper.py, libdrgn/drgn.h.in, libdrgn/linux_kernel.c, libdrgn/program.c, libdrgn/program.h, libdrgn/python/drgnpy.h, libdrgn/python/program.c, libdrgn/python/util.c
(As described in Slack)
`/proc/kcore` can only be opened by root, so live debugging has been restricted to running drgn as root. But running drgn as root has downsides:
1. The `PYTHONPATH` does not include your home directory
2. Python may drop `pyc` files as root (this can be avoided with `-B`)
3. All files and other actions your script might take are done by root.
It would be very nice to be able to run Drgn as your current user, and only use escalated privileges to open `/proc/kcore`. One approach would be to drop privileges after creating the program, which improves numbers 2 and 3. Unfortunately the PYTHONPATH, PATH, USER, and HOME environment variables would be unchanged, so much of the standard library would still believe you are root (e.g. `getpass.getuser()`). This can be worked …
=> Add the ability to run drgn against the live kernel as non-root user

drgn/cli.py, drgn/internal/sudohelper.py
A couple of followups to #347:
- Check whether sudo is installed in the first place.
- Make the sudo prompt include why we're asking for sudo.
=> Improvements to opening /proc/kcore via sudo

docs/support_matrix.rst, libdrgn/arch_ppc64.c, tests/linux_kernel/__init__.py, vmtest/__main__.py
Linux on Power support two MMU, Radix and Hash. Add page table walk to do virtual address translation for Radix MMU on BOOK3S CPU Family. Radix MMU is 4 level page table with two different page sizes to support 64K and 4K. In addition to multiple pages, Radix also supports huge pages. The implementation takes of both page sizes and huge pages.
Tested this patch with live kernel 6.3.0-rc2
drgn script:
------------
import drgn
from drgn.helpers.linux import *
prog = drgn.Program()
prog.set_kernel();
prog.load_debug_info([f'./vmlinux'])
print(cmdline(find_task(prog, 1)))
output:
------
[b'/usr/lib/systemd/systemd', b'--switched-root', b'--system', \
b'--deserialize', b'30']
=> ppc64: add virtual address translation support

_drgn.pyi, libdrgn/drgn.h.in, libdrgn/linux_kernel.c, libdrgn/program.c
Currently, when drgn is used to debug a running program, we assume it to be running on the local machine. However, with remote debugging, this will no longer be the case. To accommodate remote debugging, introduce a flag DRGN_PROGRAM_IS_LOCAL, and use it to decide whether to use /sys/module.
=> Add DRGN_PROGRAM_IS_LOCAL flag

libdrgn/debug_info.c
Rather than the indirect link between verbage in the docs and getting dependencies, just include the URL. Indent the related modules for clarity.
This might not be the most elegant way to solve this problem, but I found myself coming to this with fresh eyes today on a fresh Linux install and got lost in the weeds of yum.repos.conf and enabling the debug info repository before I eventually came around to the right documents and was reminded of the debuginfo-install command.
I'm assuming that the URL will remain stable so this will be a quality of life improvement.
=> Improve debuginfo warning

contrib/irq.py, drgn/helpers/linux/cpumask.py
script to dump irq stats.
A sample output:
python3 -m drgn -s ~/Local-vmcores/sched-study/v4.14/vmlinux -c ~/Local-vmcores/sched-study/v4.14/vmcore contrib/irq.py 
warning: could not get debugging information for:
kernel modules (could not read depmod: open: /lib/modules/4.14.307/modules.dep.bin: No such file or directory)
###################################################
List of IRQs
###################################################
irq: 0 name: timer (struct irq_desc *)0xffff9b42fd00d400  (struct irqaction *)0xffffffff88425240
irq: 1 name: i8042 (struct irq_desc *)0xffff9b42fd00d600  (struct irqaction *)0xffff9b42fcb13c00
irq: 4 name: ttyS0 (struct irq_desc *)0xffff9b42fd00dc00  (struct irqaction *)0xffff9b42fcb2bc00
irq: 8 name: rtc0 (struct irq_desc *)0xffff9b42fd00e400  (struct …
=> contrib: add script to dump irq stats. 

.packit.yaml
This partially reverts commit 002b63b43798 ("packit: disable ELN builds until fedora-eln/eln#165 is fixed"). That ELN issue was fixed, but it's still broken on s390x because of fedora-eln/eln#170.
=> packit: reenable non-s390x ELN builds

drgn/helpers/linux/wait.py, tests/linux_kernel/helpers/test_wait.py, tests/linux_kernel/kmod/drgn_test.c
Helpers to work with kernel's waitqueue subsystem
=> drgn.helpers.linux: Add helpers to work with wait-queue(s).

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, drgn/cli.py, drgn/helpers/common/format.py
Reflecting a bit of our discussion at Plumbers, I think this won't be too controversial. I've gone ahead and updated the pre-commit hooks to their latest versions, and handled any breakages there (see commit message for details). Of course, this blitzes past several tool versions which drop support for Python 3.6. So I've updated the CI to skip pre-commit/mypy on 3.6 / 3.7, and I've updated the contributing guide to explicitly state a policy on Python versions: 3.6+ is supported for building, running, & testing, but development tooling requires a non-EOL Python version.
Let me know your feelings on this, I think it will help alleviate some, but not all, of our woes with Python 3.6 support.
=> Update pre-commit hooks, dropping support for development on 3.6-3.7

libdrgn/kdump.c, libdrgn/program.c
Support for the flattened KDUMP format was added in libkdumpfile-0.5.3.
=> libdrgn: accept flattened KDUMP format

docs/_static/custom.css, docs/conf.py
For screens that aren't terribly wide, there's a break point where the current documentation design will snap to 50% width, and the text is difficult to read due to the narrow layout. Rather than using 50% as the rule, let's setup a couple good breakpoints that are wider than Alabaster's default.
In particular, at the 875px breakpoint the sidebar appears, removing 220px from the content. So add a breakpoint at 875 + 220 px, allowing the content width to grow up until that point, at which point we can cap the width.
Fixes: 98cf8d51 ("docs: make page body wider")
---
I think a video speaks a thousand words per second.
Here's before the change:
[drgn_before.webm](https://github.com/osandov/drgn/assets/5682515/dd72634d-4146-4618-95a4-dee85c3bdf8c)
And here's after: …
=> docs: Prevent jarring 50% width for medium screens

_drgn.pyi, drgn/helpers/linux/stackdepot.py, libdrgn/drgn.h, libdrgn/python/program.c, libdrgn/stack_trace.c
This helper returns a stack trace from the stack depot.
=> drgn.helpers.linux.stackdepot: add stack_depot_fetch() helper 

libdrgn/arch_aarch64.c, libdrgn/platform.h, libdrgn/program.c, libdrgn/program.h
In tag-based KASAN modes, TCR_EL1.TBI1 is enabled, which causes the top 8 bits of virtual addresses to be ignored for address translation purposes. Do the same in the page table iterator. There is no harm in doing so unconditionally, as the architecture does not support >56 bit VA sizes.
=> Apply TBI to virtual addresses on aarch64.

drgn/helpers/linux/fs.py
Starting with kernel v6.8 the mnt_list int struct mnt_namespace git converted to a rb-tree.
Reflect this change in drgn's for_each_mount() helper.
=> helpers: linux: fs: use mount rbtree instead of list

contrib/negdentdelete.py
The script is described in the docstring, but this is an interesting approach to target a directory and remove all negative dentries within it. The secret sauce is doing an `open(..., O_CREAT)`, then `unlink()` then `close()`. This ensures that the dentry for this file will be freed on `close()` rather than left as a negative dentry.
You can test it out pretty easily using my [negdentcreate](https://github.com/brenns10/kernel_stuff/tree/master/negdentcreate) tool. Here's an example.
```
stepbren at stepbren-ol9 in ~/repos/drgn (negdentdelete)
$ sudo slabtop -o | grep dentry
1244754 1243379  99%    0.19K  29637       42    237096K dentry
stepbren at stepbren-ol9 in ~/repos/drgn (negdentdelete)
$ mkdir tmp
stepbren at stepbren-ol9 in ~/repos/drgn (negdentdelete)
$ ./negdentcreate -p tmp/ -c …
```
=> contrib: add negdentdelete.py script

contrib/bpf_inspect.py
It's convenient to run drgn shell with bpf helpers in bpf_inspect.py.
=> contrib/bpf_inspect.py: add interactive mode

.packit.yaml
`drgn` no longer builds in EPEL 9 because `libkdumpfile-devel` is in RHEL 9 but not pushed out to CRB: https://issues.redhat.com/browse/RHEL-38224
Instead, let's make sure it still builds on CentOS Stream 9 + EPEL Next 9, with the `c9s-build` repo enabled, since that repo is accessible from COPR.
Fixes: #395
=> packit: replace EPEL 9 with centos-stream+epel-next-9 and c9s-build

.github/workflows/ci.yml
Our setup.py imports setuptools which is no longer provided by Python 3.12. It must be installed manually via pip. We did not notice this because the "nodeenv" package listed setuptools in its install_requires, thus providing the dependency for us.
Four hours ago nodeenv 1.9.0 was released, and it happened to drop the setuptools dependency. This broke CI. Add an explicit setuptools requirement in our pip command to fix it.
=> Fix CI failure on Python 3.12

contrib/bpf_inspect.py
Since 'prog->aux->linked_prog' has been moved to trampoline, it has to inspect linked progs from tracing link's trampoline.
Therefore, add --show-details for link command to show the linked progs for tracing link.
Example:
```bash
drgn ./contrib/bpf_inspect.py l --show-details
1: BPF_LINK_TYPE_TRACING
prog:        2: BPF_PROG_TYPE_TRACING            hid_tail_call                    __hid_bpf_tail_call
1057: BPF_LINK_TYPE_TRACING
prog:     3862: BPF_PROG_TYPE_EXT                freplace_handler                 stub_handler
target:   3861: BPF_PROG_TYPE_KPROBE             k_tcp_connect
linked:   3862: BPF_PROG_TYPE_EXT                freplace_handler
1058: BPF_LINK_TYPE_TRACING
prog:     3862: BPF_PROG_TYPE_EXT                freplace_handler                 stub_handler
target:   3860: …
```
=> contrib/bpf_inspect.py: inspect linked progs

contrib/bpf_inspect.py
Abstract bpf classes and do some enhancement.
I've test it on 6.8 and 5.15 kernels.
Here's the enhanced result:
```bash
$ sudo drgn ./contrib/bpf_inspect.py p
2: BPF_PROG_TYPE_TRACING            hid_tail_call
2295: BPF_PROG_TYPE_EXT                entry                            tail_call_reachable
2400: BPF_PROG_TYPE_EXT                entry                            tail_call_reachable
$ sudo drgn ./contrib/bpf_inspect.py m --show-details
5108: BPF_MAP_TYPE_PROG_ARRAY          prog_array
owner:    BPF_PROG_TYPE_KPROBE             JITed
idx[  0]:   4250: BPF_PROG_TYPE_KPROBE             k_tailcall
poke:       4249: BPF_PROG_TYPE_KPROBE             k_icsk_complete_hashdance        tail_call_reachable
poke:       4251: BPF_PROG_TYPE_KPROBE             k_tcp_connect …
```
=> contrib/bpf_inspect.py: abstract bpf classes

contrib/bpf_inspect.py
Show used maps and subprogs for bpf prog.
```bash
$ sudo drgn ./contrib/bpf_inspect.py p --show-details
2: BPF_PROG_TYPE_TRACING            hid_tail_call
used map:      2: BPF_MAP_TYPE_PROG_ARRAY          hid_jmp_table
2295: BPF_PROG_TYPE_EXT                entry                            tail_call_reachable
used map:   4208: BPF_MAP_TYPE_ARRAY               tailcall.bss
used map:   4207: BPF_MAP_TYPE_PROG_ARRAY          jmp_table
func[ 0]:      0: BPF_PROG_TYPE_EXT                entry                            tail_call_reachable
func[ 1]:      0: BPF_PROG_TYPE_EXT                subprog_tail
2400: BPF_PROG_TYPE_EXT                entry                            tail_call_reachable
used map:   4248: BPF_MAP_TYPE_ARRAY               tailcall.bss
used map:   4247: …
```
=> contrib/bpf_inspect.py: show used maps and subprogs for bpf prog

contrib/bpf_inspect.py
Hi, this is a totally optional PR, but I noticed that `contrib/bpf_inspect.py` uses nested f-string quotes that are only available in Python 3.12 or later. It would be nice to be able to run this on older Python versions. If @Asphaltt doesn't mind it's a simple tweak to make these work on the older versions.
=> contrib: bpf_inspect: adjust syntax for python < 3.12

tests/linux_kernel/helpers/test_stackdepot.py
TestStackDeport needs the drgn test kernel module, so if it is not present, skip the test.
Error reported:
```
ERROR: setUpClass (tests.linux_kernel.helpers.test_stackdepot.TestStackDepot)
----------------------------------------------------------------------
File "/root/drgn/tests/linux_kernel/helpers/test_stackdepot.py", line 15, in setUpClass
if not cls.prog["drgn_test_have_stackdepot"]:
KeyError: 'drgn_test_have_stackdepot'
----------------------------------------------------------------------
Ran 980 tests in 4.056s
```
=> tests/linux_kernel: Skip TestStackDepot unless test kmod is present

drgn/helpers/linux/module.py, tests/linux_kernel/helpers/test_module.py
There are a few common use cases that I find myself re-writing: iterating over the list of modules, looking up a module by name, and getting memory addresses related to modules (or vice versa). Add helpers for each.
---
I know there is the _drgn_ module API which is upcoming, and I don't necessarily want to confuse or overlap with that. So maybe it's possible this will duplicate that API in some form, but I find myself needing to access kernel modules or look them up by name/address rather frequently. So here's some code and tests (tested on 6.9 and 4.19, hoping to let CI take a look at the rest :wink: ).
=> Add linux kernel module helpers

.github/workflows/ci.yml, .github/workflows/pull_request.yml, .github/workflows/vmtest-build.yml, setup.py, vmtest/__main__.py, vmtest/download.py
This branch adds three improvements related to testing different kernel flavors:
1. Allows locally running tests against all kernel versions of a given flavor by `python setup.py test -K -f flavor`. This is just a convenience that I wanted.
2. Adds a "test-all-kernel-flavors" option similar to the "test-all-python-versions" option. Its main difference is that we don't test all flavors on push to the `main` branch (whereas we do test all Python versions for every push to `main`). I think that makes sense, because pushes to main can be rather frequent, and testing each flavor triples the test burden (which is of course multiplicative with all the Python versions). The "test-all-kernel-flavors" option is active after each vmtest build, or when the label is applied to a PR, or for a manual …
=> Add option to run CI on all kernel flavors, plus other improvements

drgn/helpers/common/memory.py, drgn/helpers/linux/mm.py, drgn/helpers/linux/slab.py, tests/linux_kernel/helpers/test_common.py
I also added a `-f` option to the `setup.py` because I wanted to run the tests locally and noticed I had no easy way to say "just run the tiny tests". I didn't bother trying to add any logic to make `-f` and `-F` conflict... it's a developer tool after all.
=> Fix test failures on SLOB / tiny

contrib/slabinfo.py, contrib/vmallocinfo.py
Add scripts to dump slabinfo and vmallocinfo.
slabinfo example output:
```
struct kmem_cache *  |         name         | active_objs  |   num_objs   | objsize  | objperslab  | pagesperslab
-------------------- | -------------------- | ------------ | ------------ | -------- | ----------- | -------------
0xffff00000632cf40   | 9p-fcall-cache       |            0 |            0 |   131192 |           1 |            64
0xffff00000632cdc0   | p9_req_t             |            0 |           33 |      248 |          33 |             2
0xffff00000632cc40   | isp1760_qh           |            0 |            0 |      144 |          28 |             1
0xffff00000632cac0   | isp1760_qtd          |            0 |            0 |      168 |          24 |             1
0xffff00000632c940   | …
```
=> contrib: Add memory related script to dump slabinfo and vmallocinfo

contrib/btrfs_print_fs_uuids_cache.py
Btrfs maintains a fs_uuids cache, but there is no defined way to look into it. This script reads the cache and prints details of the filesystems present in it.
Signed-off-by: Srivathsa Dara <srivathsa.d.dara@oracle.com>
=> contrib: add script to dump filesystem details in btrfs fs_uuids cache

libdrgn/m4/my_c_auto.m4
configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors like this aren't spotted. Notably Debian defaults to /bin/sh provided by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
=> libdrgn: fix bashism in M4 macro

drgn/helpers/linux/fs.py, tests/linux_kernel/helpers/test_fs.py
This is a bit of a drive-by helper idea, inspired by something we have in drgn-tools. We frequently want a way to just convert a dentry to a path even if we don't know the vfsmount associated with the path we want. This helper is a good way to do it. Let me know your thoughts!
=> helpers.linux.fs: add dentry_path_first_mount()

_drgn.pyi, libdrgn/cleanup.h, libdrgn/drgn.h, libdrgn/program.c, libdrgn/program.h, libdrgn/python/thread.c, tests/linux_kernel/test_threads.py, tests/test_thread.py
This PR addresses https://github.com/osandov/drgn/issues/143 by adding `name` to drgn's Thread abstraction.
This behaves differently for 3 use cases:
1. Linux kernel - Use task_struct.comm 
2. Live process - Read /proc/<tid>/comm
3. Core dump - Use fname but only valid for main thread. Returns None for other threads
Notes:
1. We do not cache thread names for Linux kernel and live process since these can change during the lifetime of the process. We do cache for core dump since this will not change
2. As a result of not caching, drgn_thread_name will malloc a new string and expect Python to free the memory when the Python object goes out of scope.
3. We assume all thread names are 16 characters including null character. Given this has been a kernel setting for awhile, I don't imagine it …
=> Add name to drgn.Thread

README.rst
This now simplifies the needed setup and therefore the documentation
here aswell.
Signed-off-by: Christian Heusel <christian@heusel.eu>
=> README.rst: the Arch Package was moved to [extra]

contrib/ptdrgn.py
See the commit message for the situation and justification. This is just a quick fix for the ptdrgn script (which I use _constantly_). But I did end up comparing against the built-in drgn CLI and noticed that the behavior on the example quoted in the commit is a bit confusing too, so I'll create a separate issue on that.
=> contrib: ptdrgn: fix FaultError when displaying objects

drgn/cli.py
Modify `_displayhook` to catch `FaultError`, log a warning, and print the `repr()` instead. Fixes #440.
=> cli: catch FaultError when displaying objects

README.rst, docs/getting_debugging_symbols.rst
I saw the pull request about Arch Linux installation and wanted to make a few similar updates:
1. `libkdumpfile` is now packaged for Arch too, so we can simplify the install steps for building from source there.
2. I wanted to include Oracle Linux instructions alongside RHEL and CentOS, especially where they differ.
So I've added steps to install Oracle Linux's officially supported drgn package (no EPEL) as a separate group. Please note that this one does contain the CTF patches downstream -- if you feel strongly about that, I can omit this, or put a warning to let people know that it has vendor modifications.
I also added steps to the documentation about getting debuginfo. I didn't want to take up a ton of space, but OL does have official documentation that covers how to get kernel …
=> Further updates to the installation instructions

drgn/helpers/linux/kallsyms.py
This is intended to be a private function. It doesn't appear in `__all__`, but the docstring still results in it being included in the Sphinx docs. Remove the docstring and verify that the function no longer appears in Sphinx.
=> kallsyms: remove docstring of _module_kallsyms()

contrib/ptdrgn.py, docs/advanced_usage.rst, drgn/cli.py, drgn/internal/repl.py, drgn/internal/rlcompleter.py
This implements #446, it's essentially the same workaround (using the internal APIs of `_pyrepl`), but I needed to make some further tweaks to get it working.
1. I stuck all of the import madness into another internal module so it only needs to be included once, not both in `cli.py` and `rlcompleter.py`.
2. I had to import readline from the `_pyrepl` package. It's honestly quite nice that this is a drop-in enough replacement. The history file works as expected without any tweaks.
3. Unfortunately, there's a `_setup()` function that resets the completer, regardless of what you have set previously. So I had to add a call to that so that our `set_completer()` call would stick.
4. Mypy is very unhappy with the use of this internal API, so we've got some `type: ignore` added to the imports.
5. …
=> Python 3.13 REPL support

contrib/bpf_inspect.py
When run drgn on kernel v5.4, there is no `tail_call_reachable`
in `prog-> aux`. Check before retrieving the struct in order to
avoid panic
=> contrib/bpf_inspect.py: fix BpfProg repr

contrib/cgroup.py, drgn/helpers/linux/cgroup.py
This is based on discussion around [cgroup.stat](https://lore.kernel.org/all/20240711025153.2356213-1-longman@redhat.com/) and as an exercise with drgn, I'm sharing it in the case anyone found that useful.
There is also a little change outside of `contrib/`.
BTW How is that with drgn and RCU protected data? Is it simply neglected and one should be ready for transient issues when dereferencing gone data (that's actually not specific to RCU) when debugging a running system?
=> Cgroup scripts

README.rst, docs/getting_debugging_symbols.rst
As of today, the Oracle Linux documentation section describing drgn has been split off into its own chapter. There are soft redirects, but update the links here so they point to the relevant content.
Also as of today, there are `python3.11-drgn` and `python3.12-drgn` packages on OL 8 and 9, so I added a brief mention that it should be possible to install drgn for newer Python versions.
=> docs: update links to Oracle Documentation

drgn/internal/repl.py
I didn't see this in practice, it's mostly out of paranoia. In particular, if `_pyrepl.readline._setup()` goes away, this will catch it.
@brenns10 any objections?
=> drgn.internal.repl: also catch AttributeError in enhanced REPL attempt

libdrgn/error.h, libdrgn/linux_kernel_helpers.c
I had opened a PR a while back for a new static inline, `drgn_error_catch()`, that makes it easier to catch all errors of a specific code, and destroy them. I tried to convert a bunch of users in that PR which made it go stale super quick. I don't really think that it's necessary to convert a bunch all in one go. So this PR just adds the helper, and does an example conversion in `libdrgn/linux_kernel_helpers.c`. That ensures that we can see how it's used and catch any errors, but it also won't conflict with the module API branch (I double-checked), and shouldn't go stale so quickly.
I think this would be a nice thing to have in general. It's also related to some of the preparatory commits I have for the CTF branch, and I figured it would be nice to keep closer to upstream by adding this …
=> Add drgn_error_catch() - take 2

libdrgn/arch_x86_64.c, libdrgn/drgn_program_parse_vmcoreinfo.inc.strswitch, libdrgn/program.h
Mark reported recursive address translation errors when debugging a QEMU guest memory dump. We're supposed to be handling this in `linux_kernel_pgtable_iterator_next_x86_64()` by translating `swapper_pg_dir` to a physical address. However, it decides whether `phys_base` was present in the VMCOREINFO by comparing `phys_base` to 0, and this dump legitimately had a `phys_base` of 0. Add a separate flag so we can distinguish missing vs 0.
@brenns10, mind sanity checking this?
=> libdrgn: x86_64: allow phys_base to be 0

README.rst
Mention that `drgn` is shipped with Ubuntu except jammy, but it's an older version
=> Update Ubuntu instructions

libdrgn/kdump.c
Adapt to libkdumpfile attribute lifetime fixes.
=> libdrgn: prepare for libkdumpfile-0.5.5

_drgn.pyi, libdrgn/drgn.h, libdrgn/python/stack_trace.c, libdrgn/stack_trace.c, tests/test_stack_trace.py
Details are in the commit message, @brenns10 does this suit your needs?
=> Make StackFrame.name fall back to symbol/PC and add StackFrame.function_name

_drgn.pyi, libdrgn/debug_info.c, libdrgn/debug_info.h, libdrgn/drgn.h, libdrgn/linux_kernel.c, libdrgn/orc_info.c, libdrgn/orc_info.h, libdrgn/python/drgnpy.h, libdrgn/python/module.c, libdrgn/python/module_section_addresses.c, libdrgn/stack_trace.c, tests/__init__.py, tests/linux_kernel/test_stack_trace.py
Thanks to your work today with 3ce0feea ("tests: don't clobber file in use by libelf") and a1869f95 ("Make StackFrame.name fall back to symbol/PC and add StackFrame.function_name"), this branch is fully unblocked!
Now that the module API has landed, we can usually rely on having a `struct drgn_module` available for a kernel module, even if the module debuginfo is not loaded (either because you have only loaded debuginfo for the kernel, or because you are using CTF). My previous ORC support required essentially re-implementing a small portion of the module API, specifically a tree that mapped address ranges to ORC data. Now, I can drop all that complexity and share this branch which I think is ready for consideration.
This branch's main goal is to enable using built-in ORC information for …
=> Support for built-in ORC information

contrib/negdentdelete.py
Accessing `dentry.d_children` fails before the lookup of `d_sib` on `struct dentry`.
```txt
File "negdentdelete.py", line 119, in main
for batch in yield_negative_dentries(prog, directory, args.chunk_size):
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "negdentdelete.py", line 52, in yield_negative_dentries
for child in for_each_child_dentry(parent):
~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
File "negdentdelete.py", line 37, in for_each_child_dentry
dentry.d_children.address_of_(),
^^^^^^^^^^^^^^^^^
AttributeError: 'struct dentry' has no member 'd_children'. Did you mean: 'd_child'?
```
=> Fix exception handling in `for_each_child_dentry`

docs/getting_debugging_symbols.rst
`command -v` is mandated by POSIX whereas `which` might not always be preset, e.g. in VMs
=> Use shell builtin instead of which

libdrgn/program.c, libdrgn/program.h, tests/test_thread.py
It appears that some core dumps may have a "pr_fname" which isn't nul-terminated, which leads to the following exception, even if you're not interested in the thread name:
```
>>> next(prog.threads()).stack_trace()
File "<console>", line 1, in <module>
Exception: pr_fname is not null terminated
```
Handle this by creating a copy and nul-terminating it.
Closes: #483
Fixes: e6cc9b07 ("Add name to drgn.Thread")
=> Handle truncated pr_fname

drgn/cli.py
For example:
```
$ python -m drgn -qp0 -e 'print_annotated_memory(prog, id(prog), 256)'
ADDRESS           VALUE
000055cf0b4c4bd0: 0000000000000006
000055cf0b4c4bd8: 00007fa1ae3fbd80 [object symbol: Program_type+0x0]
000055cf0b4c4be0: 000055cf0b4b3780
000055cf0b4c4be8: 0000000000000000
000055cf0b4c4bf0: 000055cf0b4ba560
000055cf0b4c4bf8: 0000000000000000
000055cf0b4c4c00: 0007643700000003
000055cf0b4c4c08: 0000000000000000
000055cf0b4c4c10: 000055cf0b4c4d78
000055cf0b4c4c18: 0000000000000001
000055cf0b4c4c20: 000055cf0b4c4be0
000055cf0b4c4c28: 00007fa1ae3f6400 [object symbol: drgn_language_c+0x0]
000055cf0b4c4c30: 0000000000000000
000055cf0b4c4c38: 0000000000000000
000055cf0b4c4c40: 0000000000000000
000055cf0b4c4c48: 0000000000000001
000055cf0b4c4c50: 000055cf0b4c4be0
000055cf0b4c4c58: …
```
=> Add a "-e" option to execute code provided as a command-line argument

drgn/cli.py, tests/test_cli.py
Looks like the CLI broke on Python < 3.10 with 4a6a9f33.
```
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/stepbren/repos/drgn/drgn/__main__.py", line 14, in <module>
from drgn.cli import _main
File "/home/stepbren/repos/drgn/drgn/cli.py", line 193, in <module>
class _TrySymbolsByBaseAction(argparse.Action):
File "/home/stepbren/repos/drgn/drgn/cli.py", line 214, in _TrySymbolsByBaseAction
**_bool_options(False),
TypeError: 'staticmethod' object is not callable
```
The fix is straightforward (though if you prefer a different way that's fine). I went ahead and added a smoke test that just runs …
=> Fix CLI failure on Python < 3.10 and add smoke test

drgn/cli.py, tests/test_cli.py
One fix for `-e`, plus a fix for issues with piping into drgn that a couple of people have reported recently (and a small cleanup).
=> cli: fix default program for -e and handle !isatty(stdin)

docs/getting_debugging_symbols.rst
I'm not really even sure how or why the URLs changed. Again.
=> Fix the URLs of Oracle Linux documentation

drgn/helpers/linux/fs.py, tests/linux_kernel/helpers/test_fs.py
Details are in the commit message. I'm open to a more robust method of detecting cursors, but this did the job and was simple enough.
A follow up for this is to see if I can convert the mount flags to an enum. They are currently held in an `int` so it seems reasonable, but there's only space for 4 more bits. C23 cannot come fast enough for the Linux kernel 🚀
=> drgn.helpers.linux.fs: skip cursors in for_each_mount()

libdrgn/python/object.c, libdrgn/python/type.c
Python "LazyObjects" (e.g. TypeMember) contain a callable or an object, either of which may contain a reference to the Program. When cached on the program, these references form a cycle. Add tp_traverse methods to help detect these cycles and avoid resource leakages.
=> libdrgn: python: fix reference leak for held types

libdrgn/debug_info.c, tests/test_debug_info.py
I'm not certain this is the best way to solve this, but I hate filing issues without an attempted fix.
As far as I can tell, the choice to not create all modules when default=False is a performance optimization. So I think it could be dropped given that it impacts correctness when relying on built-in ORC for unwinding.
=> libdrgn: always create all modules in load_debug_info()

drgn/helpers/linux/printk.py
Add option for human-readable timestamps to get_dmesg() and print_dmesg() by using timekeeping helpers
=> Enhance get_dmesg() and print_dmesg()

contrib/pstack.py, drgn/helpers/linux/pid.py, tests/linux_kernel/helpers/test_pid.py
I went ahead and dropped the `pstack.py` script from the `.gnu_debugdata` pull request over at #466, because it's not totally relevant. I've also been doing a lot of work on the pstack contrib script, so the copy there was outdated anyway. This version supports two modes:
```
drgn contrib/pstack.py pstack [select tasks...]
drgn contrib/pstack.py dump $OUTDIR [select tasks...]
python -m contrib.pstack print $OUTDIR
```
The second mode is better for use in the kdump environment, because it does not try to use the userspace ELF files directly, it just dumps a few pages.
=> Add contrib/pstack.py script (and helper for iterating over process threads)

drgn/commands/_builtin/crash/sys.py
Make the thread_info address output consistent with the task address output by formatting it as hexadecimal (using :x) in the string representation.
```
TASK: ffff8a7c9c5cb500  [THREAD_INFO: 18446614866536740096] 
->
TASK: ffff8a7cf10e3500  [THREAD_INFO: ffff8a7cf10e3500]
```
=> format thread_info value as hex in sys.py

vmtest/chroot.py
I am using the vmtest rootfs's to play around with crash commands on the other supported architectures. So I wanted to install crash into the rootfs. While I could have just added `crash` to the list of packages in `rootfsbuild.py`, I thought it would be nice if I didn't have to rebuild the rootfs, so I added a simple command to enter the rootfs.
=> vmtest: add vmtest.chroot to easily enter chroot

drgn/commands/_builtin/__init__.py, tests/commands/__init__.py, tests/commands/test_builtin.py
In #537 it was pointed out that the ability to pipe output produced by executing Python statements would be very useful. Unfortunately the shell redirection operators are part of the Python grammar as well, and there are many cases of ambiguity, where a command could be split into python code and shell pipeline in multiple valid ways.
However, these ambiguities may not be a dealbreaker. We can resolve them by always splitting on the first shell operator which produces a valid Python code on the left hand side. In cases where you want to force a different interpretation, you can wrap your Python code in parentheses. These ensure that any shell operator within the parentheses doesn't introduce a pipeline, because the code prior to them is incomplete without the closing parenthesis.
---
I've …
=> commands: builtin: add py command

tests/linux_kernel/tools/test_fsrefs.py
With btrfs-progs >=6.7, the default sector size is now 4096, rather than the system page size. This results in filesystems that may not be mountable, at least on some older kernels where we run vmtest. Avoid this by explicitly setting the sectorsize to the page size. Fixes #544.
=> tests: tools: fsrefs: set sector size to PAGE_SIZE

docs/advanced_usage.rst, libdrgn/linux_kernel.c, libdrgn/linux_kernel_object_find.inc.strswitch, libdrgn/program.h, tests/linux_kernel/helpers/test_sched.py, tests/linux_kernel/kmod/drgn_test.c
It looks like the linker symbols, in addition to `union thread_union`, are enough to resurrect the `THREAD_SIZE` object for all architectures! I updated the docs and included a test that uses the kmod to properly get the value and verify it. I got a clean vmtest on all architectures, at least for this helper. 
I did encounter some errors in aarch64 tiny/alternative for kernels <= 5.14, on `TestFsRefs.test_btrfs_subvolume` and `TestFsRefs::test_super_block_on_block_device`. I'll share some logs on that in the morning in a Github issue.
=> libdrgn: linux kernel: restore THREAD_SIZE object finder

drgn/helpers/linux/mm.py, scripts/generate_page_flag_getters.py
Since Linux kernel 6.18 (linux-next，“mm: introduce memdesc_flags_t”)
struct page->flags is no longer an unsigned long, but a memdesc_flags_t 
containing the actual flags in '.f'. This helper now handles both the legacy 
unsigned long flags and the new memdesc_flags_t.
Add get_page_flags() in drgn helpers to automatically handle both
cases by trying page.flags.f first and falling back to page.flags.
This fixes TypeError in drgn 0.0.32+ when running on newer kernels.
=> linux/mm: make decode_page_flags() handle memdesc_flags_t
