- drgn/helpers/linux/fs.py
BTW Thanks for adding the path_lookup function!
> Missing import for list_for_each_entry_reverse

- drgn/helpers/linux/bpf.py
- drgn/helpers/linux/cgroup.py
- drgn/helpers/linux/kernfs.py
- examples/linux/cgroup.py
- examples/linux/tcp_sock.py
- tests/helpers/linux/test_cgroup.py
- tests/helpers/linux/test_kernfs.py
Add a bunch of cgroup v2 helpers and use them in examples.
> cgroup v2 helpers

- drgn/helpers/linux/bpf.py
- examples/linux/bpf.py
Add a couple of simple BPF helpers to iterate over BPF progs and maps and an example of usage.
> BPF prog and maps helpers

- drgn/helpers/linux/net.py
- tests/helpers/linux/test_net.py
Hi Omar,
This is an "RFC" PR to add yet another helper to get `struct net` from a netns NSFS `struct file`.
As I mentioned earlier, there's no easy way to lookup netns by name, since the kernel simply doesn't maintain netns names.  So, I came up with this solution, reading the corresponding NSFS file (`/var/run/netns/$NAME`, `/var/run/docker/netns/$HASH`, etc.) directly.
AFAICT this is only useful when working on the current kernel, but I think it does provide an easy way to e.g. get `net` for a container.  What do you think?
About naming: see kernel `net/core/net_namespace.c`:`get_net_ns_by_*()` functions.
thanks,
ypl
---
Get the network namespace ("netns") descriptor ("struct net *") given an
netns NSFS pseudo-file ("struct file *") e.g. "/proc/$PID/ns/net" or
"/var/run/netns/$NAME". …
> helpers: Add get_net_ns_by_{inode,fd}()

- libdrgn/build-aux/gen_c_keywords_inc_strswitch.py
- libdrgn/language.h
- libdrgn/language_c.c
- libdrgn/lexer.h
- libdrgn/python/test.c
- libdrgn/type.c
- tests/libdrgn.py
- tests/test_language_c.py
- tests/test_program.py
Also added end to end CPP tests
This is a prerequisite to #83
Signed-off-by: prozak <nickolay.lysenko@gmail.com>
> Enable prog.type to work with classes

- .packit.yaml
Start building for the newly available chroots as well.
> packit: add s390x and build for EPEL 9 as well

- drgn/helpers/linux/slab.py
- tests/helpers/linux/test_slab.py
These are ported from https://github.com/josefbacik/debug-scripts.
> helpers:add helpers for obtaining slab objects

- libdrgn/object.c
- tests/test_object.py
Near-identical to #167, but adds partial support for floats (as opposed to integers) which ~are >64-bit, namely 80-bit x87 floats and 128-bit floats~ are not 32/64 bits.
> Partial support for floats which are not 32/64 bits

- drgn/helpers/linux/slab.py
- tests/linux_kernel/helpers/test_slab.py
When SLUB is in use, and the CONFIG_SYSFS is enabled (a very common situation), we are able to identify which slab caches have been merged. Provide a helper to expose this information so that users can lookup the correct cache name, or identify all other caches which have been merged with a given cache.
> helpers: slab: Add get_slab_aliases()

- libdrgn/dwarf_info.c
- tests/test_dwarf.py
This DWARF tag is used by C++ classes which take a variable number of template parameters, such as std::variant and std::tuple.
Signed-off-by: Alastair Robertson <ajor@meta.com>
> libdrgn: dwarf_info: Support DW_TAG_GNU_template_parameter_pack

- .packit.yaml
Per https://packit.dev/posts/copr-srpms/#deployment-phases and https://packit.dev/docs/configuration/#srpm_build_deps
> Add SRPM build deps to packit

- libdrgn/dwarf_info.c
- libdrgn/language_c.c
- tests/test_dwarf.py
Looking up objects in namespaces is already well-supported by `drgn`. These changes bring the same to functionality type lookup, so that `prog.type('struct A::B::C::MyType')` works in an analogous fashion to `prog['A::B::C::MyVar']`.
~I don't have test-cases at present because I was unsure if you'd rather tack on additional assertions to the existing namespace lookup test cases (e.g. [`TestScopes.test_namespaces_nested`](https://github.com/osandov/drgn/blob/845ac5fceb54c222d0b75d860eca8a015336c5a4/tests/test_dwarf.py#L5962-L6007)), or add entirely separate test cases. Just let me know which you prefer and I'll implement them accordingly.~
> Add support for looking up types in namespaces

- drgn/helpers/linux/slab.py
Linux commit torvalds/linux@1ad53d9fa3f6 ("slub: improve bit diffusion for freelist ptr obfuscation"), adds a swab() into the freelist_ptr() calculation. Unfortunately we can't detect this except by trial and error. The commit was added in 5.7 and has been included in stable backports, which means that pre-5.7 kernels which haven't recently been updated may still have this behavior. Add in logic to do the trial and error in order to support this oddity.
> drgn.helpers.linux.slab: Handle SLUB freelist dereference without swab()

- contrib/ps.py
New output:
```
PID     PPID    CPU  ST COMM
1       0       4    S  systemd
2       0       13   S  [kthreadd]
3       2       0    I  [rcu_gp]
4       2       0    I  [rcu_par_gp]
5       2       0    I  [slub_flushwq]
6       2       0    I  [netns]
8       2       0    I  [kworker/0:0H]
10      2       0    I  [mm_percpu_wq]
11      2       0    I  [rcu_tasks_kthre]
...
```
> enhance ps

- contrib/tcp_sock.py
Since Linux kernel commit cae3873c5b3a ("net: inet: Retire port only listening_hash") (in v5.19), listening_hash is removed and we need to iterate lhash2 table.
The script reports now:
```
LISTEN                                           [::]:22                                         [::]:0      /system.slice/sshd.service
LISTEN                                        0.0.0.0:22                                      0.0.0.0:0      /system.slice/sshd.service
LISTEN                                          [::1]:631                                        [::]:0      /system.slice/cups.service
LISTEN                                      127.0.0.1:25                                      0.0.0.0:0      /system.slice/postfix.service
LISTEN                                          [::1]:25 …
```
> port contrib/tcp_sock.py to v5.19+

- tests/linux_kernel/helpers/test_cgroup.py
> tests: add test for sock_cgroup_ptr function

- contrib/lsmod.py
Unify it with what lsmod(8) does.
> Fix output for of lsmod.py

- libdrgn/linux_kernel.c
Kernel commit ac3b43283923 ("module: replace module_layout with module_memory") in v6.4 changed the layout of `struct module`, resulting in the following drgn error [1].
Fix this by first trying to determine the base address and size of each kernel module via the `struct module_memory mem[MOD_TEXT]` member, before falling back to previous methods that work on older kernels.
Tested on v6.4-rc2 and v6.3 which does not include the above mentioned commit.
Note that kernel commit b4aff7513df3 ("scripts/gdb: use mem instead of core_layout to get the module address") performs a similar fix in Python GDB scripts.
Closes #296.
[1]
```
drgn 0.0.22 (using Python 3.11.3, elfutils 0.189, with libkdumpfile)
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, …
```
> libdrgn: linux_kernel: Fix module detection on kernel v6.4

- libdrgn/python/object.c
Running tests on Python 3.12, we get:
test_int (tests.test_language_c.TestLiteral.test_int) ... python3.12: /usr/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed. Aborted (core dumped)
We're relying on an implementation detail to check whether the object is negative. Instead, catch an overflow error, negate and try again. Genuine overflows will still overflow on the second time, but negative numbers will succeed.
> Fix test failure on Python 3.12 (fixes #298)

- contrib/btrfs_tree.py
- contrib/btrfs_tree_mod_log.py
btrfs.py is a pile of helpers Omar gave me once that I have cherished ever since. If it is already in the repo, happy to refer to it otherwise.
btrfs_tree_mod_log.py is a script I wrote to do a tree mod log search and rewind while debugging a btrfs issue.
> Add btrfs helpers to contrib

- drgn/helpers/linux/mm.py
Kernel upstream commit 1d798ca3f1 changed this, but RHEL 7 still has got old implementation, which breaks `find_containing_slab_cache()` helper
> helpers/linux/mm: support RHEL 7 compound_head implementation

- contrib/bpf_inspect.py
When run `list_bpf_progs()` in drgn shell, it's meaningless to pass `args` to `list_bpf_progs()`. Therefore, let's hide `args` from drgn shell.
BTW, select appropriate global variables and functions to run drgn shell.
So, it's ready to add more bpf functions to inspect bpf progs, bpf maps, bpf links and so on.
> contrib/bpf_inspect.py: hide args from interactive mode

- contrib/bpf_inspect.py
Like `list_bpf_progs()` and `list_bpf_maps()`, it's easy to implement `list_bpf_links()`.
Here's an use example:
```bash
drgn ./contrib/bpf_inspect.py l
1: BPF_LINK_TYPE_TRACING            prog:      2: BPF_PROG_TYPE_TRACING            hid_tail_call
931: BPF_LINK_TYPE_XDP                prog:   2056: BPF_PROG_TYPE_XDP                dummy
932: BPF_LINK_TYPE_TRACING            prog:   2060: BPF_PROG_TYPE_TRACING            fentry_xdp
933: BPF_LINK_TYPE_TRACING            prog:   2061: BPF_PROG_TYPE_TRACING            fexit_xdp
```
> contrib/bpf_inspect.py: list bpf links

- setup.py
Ok, so yesterday's solution #407 to the 3.13 wheel build failure correctly got at the root cause, but it didn't really address the issue outside of `scripts/build_manylinux_in_docker.sh`.
This solution actually will update the `build_temp` directory to contain a "t" suffix on free-threading builds, which means that we avoid issues of sharing build directories both in the wheel build environment, and in normal development.
> setup.py: use a separate build directory for free-threading python

- drgn/internal/sudohelper.py
At Meta, our Python executables are packaged in a way that doesn't leave the original .py or .pyc files easily accessible or importable. This makes the sudohelper fail with:
```
can't open file '/proc/self/fd/3/drgn/internal/sudohelper.pyc': [Errno 2] No such file or directory
```
We can work around this by passing the helper command as a string literal. It's ugly, but it works with our Meta package and with traditional installations.
@brenns10 would you mind testing this out on your systems?
> drgn.internal.sudohelper: pass privileged command as string instead of path

- .packit.yaml
Testing if fedora-eln/eln#170 is fixed.
> packit: reenable s390x ELN builds

- README.rst
> README.rst: add Gentoo package

- contrib/pp_leak/README.rst
- contrib/pp_leak/guess_leaky_skbs.py
- contrib/pp_leak/ls_pp_leaks.py
- contrib/pp_leak/scan_tcp_socks.py
- drgn/helpers/linux/net.py
Here are the scripts used in my Netdevconf 0x19 talk.
> page_pool page leak contrib scripts

- drgn/helpers/linux/kernfs.py
- tests/linux_kernel/helpers/test_kernfs.py
This PR has two commits:
* add kernfs_children() helper
* add test for kernfs_children()
This is for [issue 443](https://github.com/osandov/drgn/issues/443), as the first piece towards adding sysfs helpers.
> helpers.linux.kernfs: add kernfs_children()

- drgn/commands/_builtin/crash/ptov.py
- tests/linux_kernel/crash_commands/test_ptov.py
> crash: add ptov command
